title: [lemurodigital] # name of the site
author: scott duplessis # name of site's author
email: scott@lemuro.digital # emai l of site's author
url: https://lemuro.digital # root address of the site
baseurl: "/" # subpath of the site, e.g. "/blog"
description: > # description of the site (multiple lines allowed)
 web dev hobbyist based in Iowa City, IA. interested in open source, art history, crypto, french, data hoarding, philosophy, ecommerce, & the future. working on:

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
